<Project Sdk="Microsoft.NET.Sdk.Maui">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0-maui</TargetFramework>
    <UseMaui>true</UseMaui>
    <UseMauiResizability>true</UseMauiResizability>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Maui" Version="X.Y.Z" />
    <PackageReference Include="SkiaSharp" Version="X.Y.Z" />
  </ItemGroup>

</Project>